### ISSUE TITLE
Dead links to tutorial files

### ISSUE THREAD

**Issue by serosko** [kevlar-dev/kevlar#370]
All links pointing to the files hosted at Amazon Web Services that are required for the quick-start or mark I tutorial are dead.
The following error message is displayed when following them:
`
<Error>
<Code>NoSuchBucket</Code>
<Message>The specified bucket does not exist</Message>
<BucketName>noble-trios</BucketName>
<RequestId>50778E4182FFD860</RequestId>
<HostId>
f52Ljka1QOb0XYGKVYce2CqXtXjqXhOYuOT2osWZ/BCGgSJQZu502F5QJvVFGETq8VxeteMPQcQ=
</HostId>
</Error>
`

**Comment by standage** [comment]
Links to mock data in the quick start and the tutorial have been updated to osf.io links (details in #327). Please confirm these links work for you.

**Comment by serosko** [comment]
The links are fine now.
Small bug left: 
There is a missing pipe in the download command for the helium-config:
curl -L https://osf.io/86adm/download  sed "s:/home/user/Desktop:$(pwd):g" > helium-config.json
should be
curl -L https://osf.io/86adm/download | sed "s:/home/user/Desktop:$(pwd):g" > helium-config.json

**Comment by standage** [comment]
Good catch. Fixed in ebabd629e116cc08daf12ecdd1973c4a5d610538.
