### ISSUE TITLE
Where is kevlar?

### ISSUE THREAD

**Issue by aderzelle** [kevlar-dev/kevlar#382]
Hello,

maybe a dumb question but, after having run the pip3 install, that went smoothly, typing "kevlar" returns "command not found". 
So my question is: the pip install should install an executable right? And if yes, where is it? 

Thank you

**Comment by ctb** [comment]
hmm, that should work. What happens if you run

python -m kevlar

?

or

python -c "import kevlar"?

best,
--titus

**Comment by aderzelle** [comment]
Ok that actually works just invoking kevlar
just the autocompletion of the shell doesn't seem to recognise it, which causes some confusion on my parts. 

Thank you

**Comment by ctb** [comment]
ahh! that should be fixed if you restart your terminal session, I think,
or reset your PATH.

On Sun, Jul 05, 2020 at 08:30:21AM -0700, aderzelle wrote:
> Ok that actually works just invoking kevlar
> just the autocompletion of the shell doesn't seem to recognise it, which causes some confusion on my parts. 
> 
> Thank you 
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/kevlar-dev/kevlar/issues/382#issuecomment-653902659
-- 
C. Titus Brown, ctbrown@ucdavis.edu
